### ISSUE TITLE
Not applicable with CS1.6 KZ

### ISSUE THREAD

**Issue by a1193362693** [YaLTeR/hlkreedz#29]
Not applicable with CS1.6 KZ

Can not be used normally

**Comment by fireblizzard** [comment]
> This repository contains AMX Mod X plugins for **Half-Life** jump servers

Plugins here are only usable with Half-Life, and specifically with Adrenaline Gamer mod. We don't aim to support any other mod.
For playing Kreedz in other mods:
- Search the corresponding plugin in Alliedmods or similar sites
- or fork this one and make it compatible with your preferred mod
- or create your own plugin from scratch.
