### ISSUE TITLE
Jumpstats standup bhop stats

### ISSUE THREAD

**Issue by fireblizzard** [YaLTeR/hlkreedz#4]
When you have LJStats ON, the plugin is telling you the stats for every jump you do when doing normal bhop, and it's shown as Standup bhop. I think this makes no sense in Half-Life. The plugin was ported from CS 1.6, so it might make sense in there, but I think it's wrong to have the plugin tell your stats for every normal jump. It's annoying and useless info, as the normal way in Half-Life to move between places is to bhop unlike CS 1.6 (correct?), so you don't expect to have this info displayed nor are you going to use it in any way to improve or brag about your record Standup bhop distance (correct?).
I think the right thing would be to disable this for Half-Life and make a menu to enable it if the player really wants those Standup bhop stats to be displayed.

**Comment by YaLTeR** [comment]
In CS 1.6 you usually bhop everywhere too, however due to the rather extreme bhop cap your speed always stays pretty low. Due to abscence of bhop cap, standup bhop does indeed not make much sense in Half-Life.

**Comment by fireblizzard** [comment]
f4f1ba6 adds menu options to toggle those stats, disabled by default. You can access to the menu by saying **/ljstats** or **/jumpstats**. I guess this should be enough to solve this issue.
The toggleable jump types are:
- Longjumps
- Highjumps
- Countjumps (includes all its subtypes: _DCJ_, _MCJ_, _DropCJ_, plus normal _CJ_)
- Weirdjumps
- Bhop (inc. _BhopJump_, _StandUp BJ_, _DropBJ_)
- Ladderjumps
