### ISSUE TITLE
Tournament mode/UI

### ISSUE THREAD

**Issue by execut4ble** [YaLTeR/hlkreedz#7]
**Implement a tournament mode in HL KreedZ:**
- [x] Add a menu for picking and banning maps between two players. Map list could be taken from a txt file.
- [x] Add a .ready command when tournament mode is active, once both players are .ready, force agstart. Perhaps also agforcespectator the rest of the players in the server.

**Also some optional ones:**

- [x] Report score in chat
- [x] Automatically change to picked maps after matches

**Comment by execut4ble** [comment]
The tournament mode could get called by an admin like this for example: `kz_cup player1 player2`, after which it would prompt the map picks for specified players, as well as listening for their .ready commands.

**Comment by fireblizzard** [comment]
This is done and will be pushed after some more testing.
